language: go
install: true
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: dG2LvwcEyIZkEX9g6c1V1QGu4MrjRkkrOf7rwsGwkwu/dETqCD7GrzM6Qx1FDgSwJL38aoC6sA8C/cgf2Hn6/pSdWU/X9CkOpj3ubgfJaxPtdvDbakHY9hHXZTv3DesAsBSGa7RQKeRIOeBPEOJzjPPS5RhqQZSfj41iSlxBxVDFtDEBVWdKEQ/8qIAkJcE5iv81NuP4obDP63mi+ZKXoE0TGhQTWy/xbIc0p9M4MM246y9keJW7PSU63Lfssd6rzssWVz8y1PnO2zRigmGmu7fN6oHjvEwaNjcIe0yswzU3pJ/jLFLT3HiERQ4I3oQSKsqf9H/K+TfUMb91beepRep1kgTg0bKzpQfBGW6EjBtTVg1YqtwQ/iRvuEeM9XUN7Gc6YCiFnAkE19+S9rpFFkifNppJSGB9/rSjzaNSYiF5FIir5AWUtTIe+CznikB2kAhSwHLzN/b1MmIRBBTbAJe91bMd4abgqZDRhveK78rZOP+FJMK+89fPcgGdFs59vnYku1GikyoF1vaG6hleEFpWa/vx/sUh3vMDfWBOEwtD3buIuFFv2fNY3YzSC4blqMWSXFg0kv9pgBbYAlYwVpd1SVj4uesA/bs70b8avRrax9RdkLLDD2GR+UsUNVYiFYRG8oE05DHg9spd/MiaFbKmCi+lgLdWlWQfnwg1+tg=
  file: 
  - terraform-documenter-darwin-amd64
  - terraform-documenter-linux-amd64
  - terraform-documenter-windows-amd64
  on:
    repo: martinbaillie/terraform-documenter
    all_branches: true
    tags: true
notifications:
  email: true
